---
version: "3.3"
services:
  db:
    image: mysql:${DB_STACK_VERSION:-8.1.0}
    command: --default-authentication-plugin=mysql_native_password --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - local_mysql_data:/var/lib/mysql
    networks:
      - freer_network
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/nextcloud_db_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER_FILE=/run/secrets/nextcloud_db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - MYSQL_TCP_PORT=${DB_PORT:-3306}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mysql == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 2gb
        reservations:
          memory: 1gb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"
    secrets:
      - nextcloud_db_user
      - nextcloud_db_password
      - nextcloud_db_root_password

  app:
    # https://hub.docker.com/_/nextcloud
    image: nextcloud:${STACK_VERSION:-27.1.4-apache}
    volumes:
      - nas_conf_and_data_nfs:/var/www/html
    networks:
      - freer_network
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
      - OVERWRITEHOST=${PROXY_HOST}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=${CLI_URL}
        # https://github.com/nextcloud/docker/issues/1148#issuecomment-991697378
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - MYSQL_DATABASE_FILE=/run/secrets/nextcloud_db
      - MYSQL_USER_FILE=/run/secrets/nextcloud_db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - SMTP_PASSWORD_FILE=/run/secrets/nextcloud_db_password
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=tls
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_NAME=${SMTP_USER}
      - SMTP_AUTHTYPE=LOGIN
      - MYSQL_HOST=db:${DB_PORT:-3306}
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 2gb
        reservations:
          memory: 1gb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"
    secrets:
      - nextcloud_db
      - nextcloud_db_user
      - nextcloud_db_password
      - nextcloud_admin_user
      - nextcloud_admin_password
      - nextcloud_smtp_password

  cache:
    image: redis:${CACHE_STACK_VERSION:-7.2.3-alpine3.18}
    volumes:
      - nas_redis_data_nfs:/data
    networks:
      - freer_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 256mb
        reservations:
          memory: 128mb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"

  db_client:
    # https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin:${DB_CLIENT_STACK_VERSION:-5.2.1-apache}
    environment:
      - TZ=America/Los_Angeles
      - PMA_HOST=db
      - PMA_PORT=${DB_PORT:-3306}
    networks:
      - freer_network
    ports:
      - 8889:80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mysql == true
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 256mb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"

  db_dumper:
    # https://hub.docker.com/r/tiredofit/db-backup/
    image: tiredofit/db-backup:${DB_DUMPER_STACK_VERSION:-4.0.32}
    volumes:
      - nas_mysql_dumps_nfs:/backup
    environment:
      - TIMEZONE=America/Los_Angeles
      - CONTAINER_ENABLE_MONITORING=FALSE
      - USER_DBBACKUP=33 # nextcloud user.
      - GROUP_DBBACKUP=33 # nextcloud group on NAS.
      - DB01_TYPE=mysql
      - DB01_HOST=db
      - DB01_NAME_FILE=/run/secrets/nextcloud_db
      - DB01_USER_FILE=/run/secrets/nextcloud_db_user
      - DB01_PASS_FILE=/run/secrets/nextcloud_db_password
      - DB01_DUMP_INTERVAL=60 # Backup every 60 minutes
      - DB01_DUMP_BEGIN=+1 # (override) Backup starts immediately
      - DB01_CLEANUP_TIME=180 # (override) Cleanup backups they are older than 180 minutes
      - DB01_CHECKSUM=SHA1 # (override) Create a SHA1 checksum
      - DB01_COMPRESSION=GZ # (override) Compress with GZIP
    networks:
      - freer_network
      - freer_internal_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 256mb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"
    secrets:
      - nextcloud_db
      - nextcloud_db_user
      - nextcloud_db_password

secrets:
  nextcloud_db:
    external: true
  nextcloud_db_user:
    external: true
  nextcloud_db_password:
    external: true
  nextcloud_db_root_password:
    external: true
  nextcloud_admin_user:
    external: true
  nextcloud_admin_password:
    external: true
  nextcloud_smtp_password:
    external: true

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
  freer_internal_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  nas_conf_and_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ":/volume1/Nextcloud"
      o: "addr=nas-ii.fr33r.com"
  nas_redis_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ":/volume1/Nextcloud-Cache-Data"
      o: "addr=nas-ii.fr33r.com"
  nas_mysql_dumps_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ":/volume1/Nextcloud-Database-Backups"
      o: "addr=nas-ii.fr33r.com"
  local_mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/nextcloud/db/data"
