---
version: "3.3"

services:
  app:
    # https://github.com/stefanprodan/swarmprom/blob/master/docker-compose.yml
    image: fr33r/swarm-node-exporter:v1.3.1
    networks:
      - freer_network
    environment:
      - NODE_ID={{.Node.ID}}
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/etc/node-exporter/'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    volumes:
      - '/:/host:ro,rslave'
      - '/etc/hostname:/etc/nodename'
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
