---
version: "3.3"

services:
  node_exporter:
    # https://github.com/prometheus/node_exporter
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    volumes:
      - '/:/host:ro,rslave'
