---
version: "3.3"
# https://prometheus.io/docs/guides/dockerswarm/
# should look into this ^.
services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - freer_network
    volumes:
      - freer_prometheus_conf_nfs:/etc/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_prometheus_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/prometheus_conf'
      o: 'addr=192.168.1.2,rw'
