---
version: "3.3"
# https://prometheus.io/docs/guides/dockerswarm/
# should look into this ^.
services:
  app:
    image: prom/prometheus:${STACK_VERSION:-latest}
    user: root
    networks:
      - freer_network
    volumes:
      - nas_conf_nfs:/etc/prometheus
      - nas_data_nfs:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 256mb
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"
    configs:
      - source: prometheus.yml.v1
        target: /etc/prometheus/prometheus.yml

configs:
  prometheus.yml.v1:
    external: true

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  nas_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ":/volume1/Prometheus-Configuration"
      o: "addr=nas-ii.fr33r.com"
  nas_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ":/volume1/Prometheus-Data"
      o: "addr=nas-ii.fr33r.com"
