---
version: "3.3"
services:
  app:
    image: lscr.io/linuxserver/nzbget:${STACK_VERSION:-latest}
    networks:
      - freer_network
      - freer_internal_network
    container_name: nzbget
    environment:
      - PUID=${NZBGET_PUID}
      - PGID=${NZBGET_PGID}
      - TZ=America/Los_Angeles
      - NZBGET_USER=${USERNAME}
      - NZBGET_PASS=${PASSWORD}
    volumes:
      - freer_nas_nzbget_conf_nfs:/config
      - freer_nas_media_downloads_smb:/downloads
    ports:
      - 6789:6789
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.servertype == media
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 128mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
  freer_internal_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_nzbget_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/NZBGet-Configuration'
      o: 'addr=nas.fr33r.com'
  freer_nas_media_downloads_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.86/movie-downloads'
      o: 'vers=3.0,username=${MOVIE_DOWNLOADS_SMB_USERNAME},password=${MOVIE_DOWNLOADS_SMB_PASSWORD},uid=${NZBGET_PUID},gid=${NZBGET_PGID}'
