---
version: "3.3"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    networks:
      - freer_network
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - NZBGET_USER=${USERNAME}
      - NZBGET_PASS=${PASSWORD}
    volumes:
      - /path/to/data:/config
      - /path/to/downloads:/downloads #optional
    volumes:
      - freer_nzbget_conf_nfs:/config
      - freer_media_downloads_nfs:/downloads
    ports:
      - 6789:6789
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 512mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nzbget_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/nzbget_conf'
      o: 'addr=192.168.1.2'
  freer_media_downloads_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/media_downloads'
      o: 'addr=192.168.1.2'
