---
version: "3.3"
services:
  app:
    # https://github.com/motioneye-project/motioneye/wiki/Install-In-Docker
    image: ccrisan/motioneye:master-amd64
    networks:
      - freer_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nas_motioneye_conf_nfs:/etc/motioneye
      - nas_cctv_smb:/var/lib/motioneye
    ports:
      - 8765:8765
      - 8766:8766
    deploy:
      mode: replicated
      placement:
        constraints: [node.platform.arch == x86_64]
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 512mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  nas_motioneye_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/volume1/MotionEye-Configuration'
      o: 'addr=nas-ii.fr33r.com'
  nas_cctv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/cctv'
      o: 'addr=nas-ii.fr33r.com,username=${CCTV_SMB_USERNAME},password=${CCTV_SMB_PASSWORD}'
