---
version: "3.3"
services:
  samba:
    # https://hub.docker.com/r/dperson/samba
    image: dperson/samba
    networks:
      - freer_network
    volumes:
      - freer_samba:/mount
    ports:
      - 139:139
      - 445:445
    environment:
      TZ: PST8PDT
      SHARE: photos;/mount/photos;yes;no;no;dj,sandy,emma,fr33r,app;fr33r
      SHARE2: movies;/mount/movies;yes;no;no;dj,sandy,emma,fr33r,app;fr33r
      SHARE3: code;/mount/code;yes;no;no;fr33r,app;fr33r
      SHARE4: tv;/mount/tv;yes;no;no;dj,sandy,emma,fr33r,app;fr33r
      SHARE5: apps;/mount/apps;yes;no;no;fr33r,app;fr33r
      SHARE6: sandbox;/mount/sandbox;yes;no;no;all;fr33r
      SHARE7: nginx_conf;/mount/nginx_conf;yes;no;no;fr33r,app;fr33r
      SHARE8: nginx_ssl;/mount/nginx_ssl;yes;no;no;fr33r,app;fr33r
      SHARE9: plex_conf;/mount/plex_conf;yes;no;no;fr33r,app;fr33r
      SHARE10: nextcloud;/mount/nextcloud;yes;no;no;fr33r,app;fr33r
      USER: fr33r;${USER_PASSWORD}
      USER1: dj;${USER1_PASSWORD}
      USER2: sandy;${USER2_PASSWORD}
      USER3: emma;${USER3_PASSWORD}
      USER4: app;${USER4_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_samba:
    driver: local
    driver_opts:
      type: none
      device: /home/jon/samba/shares
      o: bind
