---
version: "3.3"
services:
  app:
    # https://hub.docker.com/_/nginx
    image: nginx
    networks:
      - freer_network
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 64mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'
    configs:
      - source: admin.fr33r.com.conf.v3
        target: /etc/nginx/conf.d/admin.fr33r.com.conf
      - source: blog.fr33r.com.conf.v1
        target: /etc/nginx/conf.d/blog.fr33r.com.conf
      - source: cams.fr33r.com.conf.v2
        target: /etc/nginx/conf.d/cams.fr33r.com.conf
      - source: collaboration.fr33r.com.conf.v1
        target: /etc/nginx/conf.d/collaboration.fr33r.com.conf
      - source: logs.fr33r.com.conf.v2
        target: /etc/nginx/conf.d/logs.fr33r.com.conf
      - source: media.fr33r.com.conf.v1
        target: /etc/nginx/conf.d/media.fr33r.com.conf
      - source: monitoring.fr33r.com.conf.v2
        target: /etc/nginx/conf.d/monitoring.fr33r.com.conf
      - source: wiki.fr33r.com.conf.v2
        target: /etc/nginx/conf.d/wiki.fr33r.com.conf
    secrets:
      - nginx_edge_cert.pem
      - nginx_edge_key.pem

configs:
  admin.fr33r.com.conf.v3:
    external: true
  blog.fr33r.com.conf.v1:
    external: true
  cams.fr33r.com.conf.v2:
    external: true
  collaboration.fr33r.com.conf.v1:
    external: true
  logs.fr33r.com.conf.v2:
    external: true
  media.fr33r.com.conf.v1:
    external: true
  monitoring.fr33r.com.conf.v2:
    external: true
  wiki.fr33r.com.conf.v2:
    external: true

secrets:
  nginx_edge_cert.pem:
    external: true
  nginx_edge_key.pem:
    external: true

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
