---
version: "3.3"
services:
  app:
    # https://hub.docker.com/_/nginx
    image: nginx
    networks:
      - freer_network
    volumes:
      - freer_nginx_conf_share:/etc/nginx/conf.d
      - freer_nginx_ssl_share:/ssl
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logstash_app:12201'
        tag: {{.Name}}

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nginx_conf_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/nginx_conf'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
  freer_nginx_ssl_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/nginx_ssl'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
