---
version: '3.3'
services:
  app:
    image: lscr.io/linuxserver/jackett:latest
    networks:
      - freer_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - freer_jackett_conf_nfs:/config
      - freer_torrent_downloads_nfs:/downloads
    ports:
      - 9117:9117
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 512mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'
             
# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_jackett_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/jackett_conf'
      o: 'addr=192.168.1.2'
  freer_torrent_downloads_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/torrent_downloads'
      o: 'addr=192.168.1.2'
