---
version: "3.3"

services:
  app:
    image: billimek/prometheus-speedtest-exporter:${STACK_VERSION:-latest}
    networks:
      - freer_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 256mb
        reservations:
          memory: 128mb
    logging:
      driver: gelf
      options:
        gelf-address: "udp://0.0.0.0:12201"
        tag: "{{.Name}}"

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
