---
version: '3.3'

services:
  app:
    # https://gohugo.io/getting-started/installing/#docker
    # https://hub.docker.com/r/klakegg/hugo/
    image: klakegg/hugo:0.101.0
    command: server
    networks:
      - freer_network
    volumes:
      - freer_hugo_blog_site_nfs:/src
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 64mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_hugo_blog_site_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/hugo_blog_site'
      o: 'addr=192.168.1.2'
