---
version: '3.4'
# https://grafana.com/blog/2022/06/02/how-to-monitor-a-tesla-with-grafana-cloud/?pg=blog&plcmt=body-txt&src=grafana_news&mdm=rss
services:
  app:
    # https://github.com/neredera/teslafi_exporter
    image: neredera/teslafi-exporter:latest
    networks:
      - freer_network
    command: "--teslafi_api_token ${API_TOKEN}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
