---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/homeassistant/home-assistant
    image: homeassistant/home-assistant:${STACK_VERSION:-latest}
    networks:
      - outside
      - freer_internal_network
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - freer_nas_home_assistant_conf_nfs:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.smarthome == true
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  outside:
    external:
      name: host
  freer_internal_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_home_assistant_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Home-Assistant-Configuration'
      o: 'addr=nas.fr33r.com'
