---
version: '3.3'

# https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
services:
  app:
    # https://hub.docker.com/r/grafana/grafana-oss
    image: grafana/grafana-oss:${STACK_VERSION:-latest}
    volumes:
      - freer_nas_grafana_conf_nfs:/var/lib/grafana
    networks:
      - freer_network
    ports:
      - 3005:3000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 128mb
        reservations:
          memory: 128mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_grafana_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Grafana-Configuration'
      o: 'addr=192.168.1.103'
