---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/adguard/adguardhome
    image: adguard/adguardhome:${STACK_VERSION:-latest}
    networks:
      - outside
    volumes:
      - freer_nas_adguard_conf_nfs:/opt/adguardhome/work
      - freer_nas_adguard_data_nfs:/opt/adguardhome/conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.servertype == media
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 256mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  outside:
    external:
      name: host

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_adguard_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Configuration'
      o: 'addr=192.168.1.103'
  freer_nas_adguard_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Data'
      o: 'addr=192.168.1.103'
