---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/linuxserver/wikijs
    image: linuxserver/wikijs:latest
    networks:
      - freer_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - freer_wikijs_conf_nfs:/config
      - freer_wikijs_data_nfs:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logstash_app:12201'
        tag: {{.Name}}

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_wikijs_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/wikijs_conf'
      o: 'addr=192.168.1.2'
  freer_wikijs_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/wikijs_data'
      o: 'addr=192.168.1.2'
