---
version: '3.3'

services:
  app:
    image: pawelmalak/flame:multiarch
    networks:
      - freer_network
    volumes:
      - freer_nas_flame_data_nfs:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    secrets:
      - flame_password
    environment:
      - PASSWORD_FILE=/run/secrets/flame_password
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 64mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_flame_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Flame-Data'
      o: 'addr=192.168.1.103'

# using Portainer to manage the creation of the secret, which is why
# we specify 'external' here.
secrets:
  flame_password:
    external: true
