---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/linuxserver/plex
    image: lscr.io/linuxserver/plex
    networks:
      - freer_network
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-5YyMzUkVz4Tvssvwg1mX
    volumes:
      - freer_plex_conf_nfs:/config
      - freer_photos_share:/photos
      - freer_movies_share:/movies
      - freer_tv_share:/tv
      - freer_music_share:/music
      - /dev/shm:/transcode
    # https://docs.linuxserver.io/images/docker-plex#hardware-acceleration
    devices:
      - /dev/dri:/dev/dri
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 2gb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_plex_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/plex_conf'
      o: 'addr=192.168.1.2'
  freer_photos_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/photos'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
  freer_tv_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/tv'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
  freer_movies_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/movies'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
  freer_music_share:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.2/music'
      o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
