---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/linuxserver/plex
    image: lscr.io/linuxserver/plex:${STACK_VERSION:-latest}
    networks:
      - freer_network
    environment:
      - PUID=1002 # UID on media server, not NAS.
      - PGID=1002 # GID on media server, not NAS.
      - VERSION=docker
    volumes:
      # using a local named bind mount for the Plex configuration for several
      # reasons, including:
      #   - better performance.
      #   - reduce issues where Plex database connections are blocked.
      #   - 'sqlite' is generally not supported on NFS.
      #     - see: https://www.sqlite.org/faq.html#q5
      #     - see: https://www.sqlite.org/search?q=nfs
      # instead the goal is to use 'rsync' to synchronize the contents of this
      # volume to the NAS, where it can be then subsequently backed up.
      - freer_local_plex_conf:/config
      # volumes for SMB shares.
      - freer_nas_photos_smb:/photos
      - freer_nas_movies_smb:/movies
      - freer_nas_tv_smb:/tv
      - freer_nas_music_smb:/music
      # local bind mount for ramdisk. used to speed up performance of transcoding.
      - /dev/shm:/transcode
    # https://docs.linuxserver.io/images/docker-plex#hardware-acceleration
    devices:
      - /dev/dri:/dev/dri
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.servertype == media
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 2gb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_local_plex_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/plex/config'
  freer_nas_photos_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/photos'
      o: 'addr=nas-ii.fr33r.com,username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_tv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/tv'
      o: 'addr=nas-ii.fr33r.com,username=${TV_SMB_USERNAME},password=${TV_SMB_PASSWORD}'
  freer_nas_movies_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/movies'
      o: 'addr=nas-ii.fr33r.com,username=${MOVIES_SMB_USERNAME},password=${MOVIES_SMB_PASSWORD}'
  freer_nas_music_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/music'
      o: 'addr=nas-ii.fr33r.com,username=${MUSIC_SMB_USERNAME},password=${MUSIC_SMB_PASSWORD}'
