---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/linuxserver/plex
    image: lscr.io/linuxserver/plex
    networks:
      - freer_network
    environment:
      - PUID=1002
      - PGID=1002
      - VERSION=docker
    volumes:
      - freer_nas_plex_conf_nfs:/config
      - freer_nas_photos_smb:/photos
      - freer_nas_movies_smb:/movies
      - freer_nas_tv_smb:/tv
      - freer_nas_music_smb:/music
      - /dev/shm:/transcode
    # https://docs.linuxserver.io/images/docker-plex#hardware-acceleration
    devices:
      - /dev/dri:/dev/dri
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == red
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 2gb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_plex_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Plex-Configuration'
      o: 'addr=192.168.1.103'
  freer_nas_photos_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/photos'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_tv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/tv'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_movies_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/movies'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_music_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/music'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
