---
version: '3.3'

services:
  app:
    image: docker.elastic.co/logstash/logstash:8.2.3
    networks:
      - freer_network
    volumes:
      - freer_logstash_conf_nfs:/etc/logstash
    command: 'logstash -f /etc/logstash/logstash.conf'
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure 
        max_attempts: 3 
        
# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_logstash_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/logstash_conf'
      o: 'addr=192.168.1.2'
