version: '3.2'

# derived from https://docs.portainer.io/v/ce-2.9/start/install/server/swarm/linux.
services:
  agent:
    image: portainer/agent:${STACK_VERSION:-2.15.1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - freer_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          memory: 32mb
        reservations:
          memory: 32mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

  app:
    image: portainer/portainer-ce:${STACK_VERSION:-2.15.1}
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data_nfs:/data
    networks:
      - freer_network
    ports:
      - 9000:9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 128mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  portainer_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/portainer'
      o: 'addr=192.168.1.2'
