---
version: "3.3"
services:
  app:
    image: lscr.io/linuxserver/syncthing:latest
    networks:
      - freer_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - freer_syncthing_conf_nfs:/config
      - /home/jon/samba:/samba
      - /home/jon/nfs:/nfs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure 
        max_attempts: 3 
      placement:
        constraints:
          - node.hostname == red
      resources:
        limits:
          memory: 512mb

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_syncthing_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/home/jon/nfs/exports/syncthing_conf'
      o: 'addr=192.168.1.2'
