---
version: '3.3'

services:
  app:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    networks:
      - freer_network
    volumes:
      - freer_nas_kibana_conf_nfs:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://${ELASTICSEARCH_HOST}:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/run/secrets/elasticsearch_single_node_cert
    ports:
      - 5601:5601
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.elk == true
      restart_policy:
        condition: on-failure 
        max_attempts: 3 
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 512mb
    secrets:
      - source: elasticsearch_single_node_cert
        target: elasticsearch_single_node_cert
        # https://discuss.elastic.co/t/docker-setup-generated-certs-logstash-permission-denied/301133
        # https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
        uid: '1000'
        gid: '0'
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
        
# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

secrets:
  elasticsearch_single_node_cert:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_kibana_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Kibana-Configuration'
      o: 'addr=nas.fr33r.com'
