---
version: '3.3'

services:
  app:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    networks:
      - freer_network
    environment:
      - discovery.type=single-node
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure 
        max_attempts: 3 
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logstash_app:12201'
        tag: {{.Name}}
        
# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

