---
version: "3.3"
services:
  app:
    # https://hub.docker.com/r/linuxserver/bazarr
    image: linuxserver/bazarr:${STACK_VERSION:-latest}
    networks:
      - freer_network
      - freer_internal_network
    environment:
      - PUID=${BAZARR_PUID}
      - PGID=${BAZARR_PGID}
      - TZ=America/Los_Angeles
    volumes:
      - nas_conf_nfs:/config
      - nas_movies_smb:/movies
      - nas_tv_smb:/tv
    ports:
      - 6767:6767
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.servertype == media
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 512mb
        reservations:
          memory: 256mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
  freer_internal_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  nas_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/volume1/Bazarr-Configuration'
      o: 'addr=nas-ii.fr33r.com'
  nas_movies_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/movies'
      o: 'addr=nas-ii.fr33r.com,username=${MOVIES_SMB_USERNAME},password=${MOVIES_SMB_PASSWORD},uid=1018,gid=1001'
  nas_tv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas-ii.fr33r.com/tv'
      o: 'addr=nas-ii.fr33r.com,username=${TV_SMB_USERNAME},password=${TV_SMB_PASSWORD},uid=${BAZARR_PUID},gid=${BAZARR_PGID}'
