---
version: "3.3"

services:
  app:
    image: ghcr.io/blakeblackshear/frigate:${STACK_VERSION:-stable}
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.smarthome == true
      restart_policy:
        condition: on-failure
        max_attempts: 3 
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'
    devices:
      - /dev/dri:/dev/dri #Intel HWA
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - freer_nas_frigate_conf_nfs:/config
      - freer_nas_cctv_smb:/media/frigate
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  outside:
    external:
      name: host

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_frigate_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Frigate-Configuration'
      o: 'addr=nas.fr33r.com'
  freer_nas_cctv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas.fr33r.com/cctv'
      o: 'username=${CCTV_SMB_USERNAME},password=${CCTV_SMB_PASSWORD}'
