---
version: "3.3"
services:
  app:
    # https://docs.linuxserver.io/images/docker-duplicati
    image: lscr.io/linuxserver/duplicati:${STACK_VERSION:-latest}
    networks:
      - freer_network
      - freer_internal_network
    environment:
      - PUID=0 # root
      - PGID=0 # root
      - TZ=America/Los_Angeles
    ports:
      - 8200:8200
    volumes:
      - freer_nas_duplicati_conf_nfs:/config
        # backup volumes.
      - freer_nas_photo_backups_nfs:/backups/photos
      - freer_nas_movie_backups_nfs:/backups/movies
      - freer_nas_tv_backups_nfs:/backups/tv
      - freer_nas_music_backups_nfs:/backups/music
      - freer_nas_radarr_backups_nfs:/backups/conf/radarr
      - freer_nas_jackett_backups_nfs:/backups/conf/jackett
      - freer_nas_nzbget_backups_nfs:/backups/conf/nzbget
      - freer_nas_duplicati_backups_nfs:/backups/conf/duplicati
      - freer_nas_plex_backups_nfs:/backups/conf/plex
      - freer_nas_prometheus_conf_backups_nfs:/backups/conf/prometheus
      - freer_nas_portainer_data_backups_nfs:/backups/data/portainer
      - freer_nas_portainer_conf_backups_nfs:/backups/conf/portainer
      - freer_nas_prometheus_data_backups_nfs:/backups/data/prometheus
      - freer_nas_grafana_backups_nfs:/backups/conf/grafana
      - freer_nas_omv_backups_nfs:/backups/omv
      - freer_nas_adguard_conf_backups_nfs:/backups/conf/adguard
      - freer_nas_adguard_data_backups_nfs:/backups/data/adguard
        # source volumes.
      - freer_nas_photos_smb:/sources/photos
      - freer_nas_movies_smb:/sources/movies
      - freer_nas_music_smb:/sources/music
      - freer_nas_tv_smb:/sources/tv
      - freer_nas_plex_conf_nfs:/sources/conf/plex
#     - freer_wikijs_conf_nfs:/sources/wikijs/configuration
#     - freer_wikijs_data_nfs:/sources/wikijs/data
      - freer_nas_radarr_conf_nfs:/sources/conf/radarr
#     - freer_elasticsearch_certs_nfs:/sources/elasticsearch/certs
#     - freer_elasticsearch_conf_nfs:/sources/elasticsearch/configuration
      - freer_nas_grafana_conf_nfs:/sources/conf/grafana
      - freer_nas_jackett_conf_nfs:/sources/conf/jackett
#     - freer_kibana_conf_nfs:/sources/kibana/configuration
#     - freer_logstash_pipeline_conf_nfs:/sources/logstash/pipelines
#     - freer_nextcloud_nfs:/sources/nextcloud
#     - freer_nginx_conf_share:/sources/nginx/configuration
#     - freer_nginx_ssl_share:/sources/nginx/ssl
      - freer_nas_nzbget_conf_nfs:/sources/conf/nzbget
      - freer_nas_prometheus_conf_nfs:/sources/conf/prometheus
      - freer_nas_prometheus_data_nfs:/sources/data/prometheus
      - portainer_nas_data_nfs:/sources/data/portainer
#     - freer_syncthing_conf_nfs:/sources/syncthing/configuration
      - freer_nas_adguard_conf_nfs:/sources/conf/adguard
      - freer_nas_adguard_data_nfs:/sources/data/adguard
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 128mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true
  freer_internal_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_duplicati_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Duplicati-Configuration'
      o: 'addr=nas.fr33r.com'
  # backup volumes.
  freer_nas_photo_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Photo-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_movie_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Movie-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_tv_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/TV-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_music_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Music-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_duplicati_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Duplicati-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_radarr_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Radarr-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_jackett_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Jackett-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_nzbget_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/NZBGet-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_plex_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Plex-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_grafana_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Grafana-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_prometheus_conf_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Prometheus-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_prometheus_data_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Prometheus-Data-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_portainer_data_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Portainer-Data-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_portainer_conf_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Portainer-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_omv_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/OMV-Backup'
      o: 'addr=nas.fr33r.com'
  freer_nas_adguard_conf_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Configuration-Backups'
      o: 'addr=nas.fr33r.com'
  freer_nas_adguard_data_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Data-Backups'
      o: 'addr=nas.fr33r.com'
  # source volumes.
  freer_nas_photos_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas.fr33r.com/photos'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_tv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas.fr33r.com/tv'
      o: 'username=${TV_SMB_USERNAME},password=${TV_SMB_PASSWORD}'
  freer_nas_movies_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas.fr33r.com/movies'
      o: 'username=${MOVIES_SMB_USERNAME},password=${MOVIES_SMB_PASSWORD}'
  freer_nas_music_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//nas.fr33r.com/music'
      o: 'username=${MUSIC_SMB_USERNAME},password=${MUSIC_SMB_PASSWORD}'
  # plex.
  freer_nas_plex_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Plex-Configuration'
      o: 'addr=nas.fr33r.com'
# # wikijs.
# freer_wikijs_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/wikijs_conf'
#     o: 'addr=192.168.1.2'
# freer_wikijs_data_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/wikijs_data'
#     o: 'addr=192.168.1.2'
  # radarr.
  freer_nas_radarr_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Radarr-Configuration'
      o: 'addr=nas.fr33r.com'
# # elasticsearch.
# freer_elasticsearch_certs_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/elasticsearch_certs'
#     o: 'addr=192.168.1.2'
# freer_elasticsearch_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/elasticsearch_conf'
#     o: 'addr=192.168.1.2'
  # grafana.
  freer_nas_grafana_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Grafana-Configuration'
      o: 'addr=nas.fr33r.com'
  # jackett.
  freer_nas_jackett_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Jackett-Configuration'
      o: 'addr=nas.fr33r.com'
# # kibana.
# freer_kibana_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/kibana_conf'
#     o: 'addr=192.168.1.2'
# # logstash.
# freer_logstash_pipeline_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/logstash_pipeline_conf'
#     o: 'addr=192.168.1.2'
# # nextcloud.
# freer_nextcloud_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/nextcloud'
#     o: 'addr=192.168.1.2'
  # nzbget.
  freer_nas_nzbget_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/NZBGet-Configuration'
      o: 'addr=nas.fr33r.com'
  # prometheus.
  freer_nas_prometheus_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Prometheus-Configuration'
      o: 'addr=nas.fr33r.com'
  freer_nas_prometheus_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Prometheus-Data'
      o: 'addr=nas.fr33r.com'
  # portainer.
  portainer_nas_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Portainer-Configuration'
      o: 'addr=nas.fr33r.com'
  # adguard.
  freer_nas_adguard_conf__nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Configuration'
      o: 'addr=nas.fr33r.com'
  freer_nas_adguard_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/AdGuard-Data'
      o: 'addr=nas.fr33r.com'
