---
version: "3.3"
services:
  app:
    # https://docs.linuxserver.io/images/docker-duplicati
    image: lscr.io/linuxserver/duplicati:latest
    networks:
      - freer_network
    environment:
      - PUID=0 # root
      - PGID=0 # root
      - TZ=America/Los_Angeles
    ports:
      - 8200:8200
    volumes:
      - freer_nas_duplicati_conf_nfs:/config
        # backup volumes.
      - freer_nas_photo_backups_nfs:/backups/photos
      - freer_nas_movie_backups_nfs:/backups/movies
      - freer_nas_tv_backups_nfs:/backups/tv
      - freer_nas_music_backups_nfs:/backups/music
#     - freer_app_backups_nfs:/backups/app
#     - freer_db_backups_nfs:/backups/db
        # source volumes.
      - freer_nas_photos_smb:/sources/photos
      - freer_nas_movies_smb:/sources/movies
      - freer_nas_music_smb:/sources/music
      - freer_nas_tv_smb:/sources/tv
      - freer_nas_plex_conf_nfs:/sources/conf/plex
#     - freer_wikijs_conf_nfs:/sources/wikijs/configuration
#     - freer_wikijs_data_nfs:/sources/wikijs/data
      - freer_nas_radarr_conf_nfs:/sources/conf/radarr
#     - freer_elasticsearch_certs_nfs:/sources/elasticsearch/certs
#     - freer_elasticsearch_conf_nfs:/sources/elasticsearch/configuration
#     - freer_grafana_conf_nfs:/sources/grafana/configuration
      - freer_nas_jackett_conf_nfs:/sources/conf/jackett
#     - freer_kibana_conf_nfs:/sources/kibana/configuration
#     - freer_logstash_pipeline_conf_nfs:/sources/logstash/pipelines
#     - freer_nextcloud_nfs:/sources/nextcloud
#     - freer_nginx_conf_share:/sources/nginx/configuration
#     - freer_nginx_ssl_share:/sources/nginx/ssl
      - freer_nas_nzbget_conf_nfs:/sources/conf/nzbget
#     - freer_prometheus_conf_nfs:/sources/prometheus/configuration
#     - freer_prometheus_data_nfs:/sources/prometheus/data
#     - freer_syncthing_conf_nfs:/sources/syncthing/configuration
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3 
      resources:
        limits:
          memory: 128mb
        reservations:
          memory: 64mb
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://0.0.0.0:12201'
        tag: '{{.Name}}'

# have to reference external network, otherwise a new scoped network is
# created during stack deploy.
# https://docs.docker.com/compose/compose-file/#external
networks:
  freer_network:
    external: true

# have to replicate dependent volume definitions
# to ensure all nodes are setup correctly.
# https://docs.docker.com/compose/compose-file/#volumes-top-level-element
volumes:
  freer_nas_duplicati_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Duplicati-Configuration'
      o: 'addr=192.168.1.103'
  # backup volumes.
  freer_nas_photo_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Photo-Backups'
      o: 'addr=192.168.1.103'
  freer_nas_movie_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Movie-Backups'
      o: 'addr=192.168.1.103'
  freer_nas_tv_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/TV-Backups'
      o: 'addr=192.168.1.103'
  freer_nas_music_backups_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Music-Backups'
      o: 'addr=192.168.1.103'
# freer_app_backups_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/app_backups'
#     o: 'addr=192.168.1.2'
# freer_db_backups_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/db_backups'
#     o: 'addr=192.168.1.2'
  # source volumes.
  freer_nas_photos_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/photos'
      o: 'username=${PHOTOS_SMB_USERNAME},password=${PHOTOS_SMB_PASSWORD}'
  freer_nas_tv_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/tv'
      o: 'username=${TV_SMB_USERNAME},password=${TV_SMB_PASSWORD}'
  freer_nas_movies_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/movies'
      o: 'username=${MOVIES_SMB_USERNAME},password=${MOVIES_SMB_PASSWORD}'
  freer_nas_music_smb:
    driver: local
    driver_opts:
      type: cifs
      device: '//192.168.1.103/music'
      o: 'username=${MUSIC_SMB_USERNAME},password=${MUSIC_SMB_PASSWORD}'
  # plex.
  freer_nas_plex_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Plex-Configuration'
      o: 'addr=192.168.1.103'
# # wikijs.
# freer_wikijs_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/wikijs_conf'
#     o: 'addr=192.168.1.2'
# freer_wikijs_data_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/wikijs_data'
#     o: 'addr=192.168.1.2'
  # radarr.
  freer_nas_radarr_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Radarr-Configuration'
      o: 'addr=192.168.1.103'
# # elasticsearch.
# freer_elasticsearch_certs_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/elasticsearch_certs'
#     o: 'addr=192.168.1.2'
# freer_elasticsearch_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/elasticsearch_conf'
#     o: 'addr=192.168.1.2'
# # grafana.
# freer_grafana_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/grafana_conf'
#     o: 'addr=192.168.1.2'
  # jackett.
  freer_nas_jackett_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/Jackett-Configuration'
      o: 'addr=192.168.1.103'
# # kibana.
# freer_kibana_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/kibana_conf'
#     o: 'addr=192.168.1.2'
# # logstash.
# freer_logstash_pipeline_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/logstash_pipeline_conf'
#     o: 'addr=192.168.1.2'
# # nextcloud.
# freer_nextcloud_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/nextcloud'
#     o: 'addr=192.168.1.2'
# # nginx.
# freer_nginx_conf_share:
#   driver: local
#   driver_opts:
#     type: cifs
#     device: '//192.168.1.2/nginx_conf'
#     o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
# freer_nginx_ssl_share:
#   driver: local
#   driver_opts:
#     type: cifs
#     device: '//192.168.1.2/nginx_ssl'
#     o: 'username=app,password=${SAMBA_APP_SHARE_PASSWORD}'
  # nzbget.
  freer_nas_nzbget_conf_nfs:
    driver: local
    driver_opts:
      type: nfs
      device: ':/export/NZBGet-Configuration'
      o: 'addr=192.168.1.103'
# # prometheus.
# freer_prometheus_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/prometheus_conf'
#     o: 'addr=192.168.1.2'
# freer_prometheus_data_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/prometheus_data'
#     o: 'addr=192.168.1.2'
# # syncthing.
# freer_syncthing_conf_nfs:
#   driver: local
#   driver_opts:
#     type: nfs
#     device: ':/home/jon/nfs/exports/syncthing_conf'
#     o: 'addr=192.168.1.2'
